http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    flask-native-strip:
      stripPrefix:
        prefixes:
          - "/app"

  routers:
    http-to-https:
      entryPoints:
        - web
      rule: Host(`dmikes.duckdns.org`)
      middlewares:
        - redirect-to-https
      service: noop@internal

    flask-native:
      rule: "Host(`dmikes.duckdns.org`) && PathPrefix(`/app`)"
      entryPoints:
        - websecure
      service: flask-native
      tls:
        certResolver: myresolver
      middlewares:
        - flask-native-strip

  services:
    flask-native:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5001"

tls:
  options:
    default:
      minVersion: VersionTLS12
